---
clickhouse:
  hosts:
    click:
      ansible_host: 51.250.13.148
      ansible_user: "berezhok"

    vector:
      ansible_host: 51.250.8.214
      ansible_user: "berezhok"
      
    lighthouse:
      ansible_host: 51.250.79.135
      ansible_user: "berezhok"

